### PR TITLE
Fix Varint decoding and process length only if field is length-encoded.

### PR DESCRIPTION
**Pull request by Borisvl**
Thanks a lot for open-sourcing your project! Adopting your code helped me a lot while working on my own little project - creating a IR remote control for Spotify. 

While I was debugging to find a problem, I stumpled upon a small error in the varint encoding: Varints store numbers with the least significant group first, which can lead to subtle bugs for ints > 128.

### CODE REVIEW

**Comment by andrasbiro** [comment]
Glad I was able to help. On your modifications:
- on the first one, the byte endianness fix - have you tested this? I would agree with your fix based on the documentation, but I think did test the varint decoding with > 128. Since a varint holds the length of the entire message, it is pretty simple to have an application status message which is longer, and it did work for me, though honestly, I'm not sure why.
- The second one (wire==2) removes unused, but documented functionality. pbDecodeHeader can decode wire==0, which is a single varint. See here: https://github.com/andrasbiro/ArduCastControl/blob/main/ArduCastControl.h#L260

**Comment by Borisvl** [comment]
1. Yes, I tested the fix. I was also wondering why it did not trigger any problem, but I guess it is because a/ usually the existing code produces varints greater than the right one, b/ ArduinoJson seems to stop deserialization when the json input is finished and hence does not create errors when the length is too big.
2. True, I did not see that the behaviour is well documented!

**Comment by andrasbiro** [comment]
Strange. I planned to work on other aspects of this project this week anyway, I will double check how the length is decoded with long messages.

**Comment by andrasbiro** [comment]
You are 100% correct, including the part that it worked because the bug usually resulted bigger value than the correct one. Since the json is the only one that can be affected by this, and it's also the last member of the message, I haven't found the bug myself.

**Comment by andrasbiro** [comment]
Do you have anything else coming maybe? I think this bugfix is worth a version number bump, but if you are working on something else, I'll wait for it.

**Pull request merged**
